apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: root-password
    remoteRef:
      key: mongodb-root-password
  - secretKey: connection-string
    remoteRef:
      key: mongodb-connection-string