apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  provider:
    azurekv:
      # Key Vault URL comes from Terraform output
      vaultUrl: {{ .Values.azure.keyVaultUri | quote }}
      tenantId: {{ .Values.azure.tenantId | quote }}
      authType: ManagedIdentity
      # Use AKS managed identity for authentication
      managedIdentity:
        clientId: "c4e85c7c-4c52-48f7-9ba1-c6b8a76089af"