apiVersion: v1
kind: Service
metadata:
  name: todo-app
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}