apiVersion: v2
name: infrastructure
description: Infrastructure components for todo-app (NGINX Ingress, etc.)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled