# Production environment values for todo-app
replicaCount: 3

image:
  repository: todoapp
  pullPolicy: Always
  tag: "stable"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: todo-app.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: todo-app-tls
      hosts:
        - todo-app.yourdomain.com

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - todo-app
          topologyKey: kubernetes.io/hostname

# MongoDB configuration for production
mongodb:
  enabled: true
  auth:
    enabled: true
    rootUser: "admin"
    existingSecret: "mongodb-secret"
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "managed-premium"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  replicaSet:
    enabled: true
    replicas:
      secondary: 2
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM

# Security configurations
podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Azure Key Vault integration
keyVault:
  enabled: true
  name: "kv-todo-app-prod"
  secrets:
    - secretName: "mongodb-connection-string"
      objectName: "mongodb-connection-string"
    - secretName: "app-secret-key"
      objectName: "app-secret-key"

# Network policies
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb
      ports:
        - protocol: TCP
          port: 8080

# Environment-specific labels
labels:
  environment: "production"
  team: "platform"
  cost-center: "engineering"