apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  provider:
    azurekv:
      # Key Vault URL comes from Terraform output
      vaultUrl: {{ .Values.azure.keyVaultUri | quote }}

      # Azure AD Tenant ID comes from Terraform output
      tenantId: {{ .Values.azure.tenantId | quote }}

      # Use Managed Identity for authentication
      authType: ManagedIdentity

      # Use AKS managed identity client ID for authentication
      identityId: "c4e85c7c-4c52-48f7-9ba1-c6b8a76089af"