apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  provider:
    azurekv:
      # Key Vault URL comes from Terraform output
      vaultUrl: {{ .Values.azure.keyVaultUri | quote }}

      # Azure AD Tenant ID comes from Terraform output
      tenantId: {{ .Values.azure.tenantId | quote }}

      # Use Workload Identity for authentication (AKS managed identity)
      authType: WorkloadIdentity

      serviceAccountRef:
        name: {{ .Values.serviceAccount.name | default "default" }}