apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  provider:
    azurekv:
      # Key Vault URL comes from Terraform output
      vaultUrl: {{ .Values.azure.keyVaultUri | quote }}

      # Azure AD Tenant ID comes from Terraform output
      tenantId: {{ .Values.azure.tenantId | quote }}

      # Use Managed Identity for authentication (AKS managed identity)
      authType: ManagedIdentity

      # AKS managed identity object ID (not client ID)
      identityId: {{ .Values.azure.objectId | quote }}