apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Values.namespace | default "todo-app" }}
spec:
  provider:
    azurekv:
      # Key Vault URL comes from Terraform output
      vaultUrl: {{ .Values.azure.keyVaultUri | quote }}

      # Azure AD Tenant ID
      tenantId: {{ .Values.azure.tenantId | quote }}

      # Use Service Principal authentication with credentials stored in Kubernetes Secret
      authType: ServicePrincipal

      authSecretRef:
        clientId:
          name: {{ .Values.azure.secretName | default "azure-secret-sp" }}
          key: ClientID
        clientSecret:
          name: {{ .Values.azure.secretName | default "azure-secret-sp" }}
          key: ClientSecret