apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values - these should be replaced with actual values
  # For MongoDB in same cluster: mongodb://mongodb-service:27017/TodoApp
  # For external MongoDB: mongodb://username:password@host:port/database
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZTo2MjcxNy9Ub2RvQXBw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  database-name: "TodoApp"
  collection-name: "Todos"