apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: application
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: "todo-app=haffy/todo-app"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-branch: "master"
    argocd-image-updater.argoproj.io/update-strategy: "semver"
    argocd-image-updater.argoproj.io/write-back-target: "helm/todo-app/values.yaml:image.tag"
    # Git credentials for write-back
    argocd-image-updater.argoproj.io/git-repository: "https://github.com/sirhaffy/clo-k8s-inl01.git"
    # Source refresh configuration
    argocd.argoproj.io/refresh: 'hard'  # Force refresh cache
    argocd.argoproj.io/sync-wave: '0'   # Sync priority
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source repository configuration
  source:
    repoURL: https://github.com/sirhaffy/clo-k8s-inl01.git
    targetRevision: HEAD
    path: helm/todo-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        # Remove image.tag override - let Image Updater manage it via values.yaml
        - name: replicaCount
          value: "2"

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app

  # Sync policy for automatic deployment
  syncPolicy:
    automated:
      prune: true          # Remove resources that are no longer in Git
      selfHeal: true       # Automatically fix drift from desired state
      allowEmpty: false    # Don't sync if source is empty
    syncOptions:
      - CreateNamespace=true    # Create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true         # Prune resources last
      - ApplyOutOfSyncOnly=true # Only apply resources that are out of sync
    retry:
      limit: 5               # Max retry attempts
      backoff:
        duration: 5s         # Initial retry delay
        factor: 2            # Backoff factor
        maxDuration: 3m      # Maximum retry delay

  # Refresh configuration - how often ArgoCD checks for changes
  info:
    - name: 'Refresh Interval'
      value: '3m'          # Check for Git changes every 3 minutes

  # Health check configuration
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas    # Ignore replica differences (for HPA)
    - group: ""
      kind: Secret
      jsonPointers:
        - /data           # Ignore secret data changes from external sources

  # Revision history limit
  revisionHistoryLimit: 10