apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: 'normal'
    argocd.argoproj.io/sync-wave: '0'   # Deploy after secrets

spec:
  project: todo-app-project

  # Source repository and path for MongoDB chart
  source:
    repoURL: https://github.com/sirhaffy/clo-k8s-inl01.git
    targetRevision: master
    path: helm/mongodb
    helm:
      valueFiles:
        - values.yaml

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app

  # Sync policy for automatic deployment
  syncPolicy:
    automated:
      prune: true               # Remove resources that are no longer in Git
      selfHeal: true            # Automatically fix drift from desired state
      allowEmpty: false         # Don't sync if source is empty
    syncOptions:
      - CreateNamespace=true    # Create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true          # Prune resources last
    retry:
      limit: 5                  # Max retry attempts
      backoff:
        duration: 5s            # Initial retry delay
        factor: 2               # Backoff factor
        maxDuration: 3m         # Maximum retry delay

  # Health check configuration
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas        # Ignore replica drift