apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
data:
  # Service configuration for notifications
  service.webhook.generic: |
    url: https://hooks.slack.com/workflows/YOUR_SLACK_WEBHOOK_URL
    headers:
    - name: Content-Type
      value: application/json

  service.email.gmail: |
    username: $email-username
    password: $email-password
    host: smtp.gmail.com
    port: 587
    from: $email-username

  # Template definitions
  template.app-deployed: |
    email:
      subject: "Application {{.app.metadata.name}} deployed to {{.app.spec.destination.namespace}}"
    message: |
      Application {{.app.metadata.name}} has been successfully deployed to {{.app.spec.destination.namespace}}.

      Revision: {{.app.status.sync.revision}}
      Repository: {{.app.spec.source.repoURL}}
      Path: {{.app.spec.source.path}}

      Sync Status: {{.app.status.sync.status}}
      Health Status: {{.app.status.health.status}}

      Time: {{.app.status.operationState.finishedAt}}

  template.app-health-degraded: |
    email:
      subject: "Application {{.app.metadata.name}} health degraded"
    message: |
      Application {{.app.metadata.name}} health status changed to {{.app.status.health.status}}.

      Application details:
      - Name: {{.app.metadata.name}}
      - Namespace: {{.app.spec.destination.namespace}}
      - Health Status: {{.app.status.health.status}}
      - Sync Status: {{.app.status.sync.status}}

      Please check the application immediately.

  template.app-sync-failed: |
    email:
      subject: "Application {{.app.metadata.name}} sync failed"
    message: |
      Application {{.app.metadata.name}} sync operation failed.

      Error message: {{.app.status.operationState.message}}

      Application details:
      - Name: {{.app.metadata.name}}
      - Namespace: {{.app.spec.destination.namespace}}
      - Repository: {{.app.spec.source.repoURL}}
      - Revision: {{.app.status.sync.revision}}

      Please investigate and resolve the issue.

  template.app-sync-succeeded: |
    webhook:
      generic:
        method: POST
        body: |
          {
            "text": "✅ Application {{.app.metadata.name}} sync succeeded",
            "attachments": [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "Application",
                    "value": "{{.app.metadata.name}}",
                    "short": true
                  },
                  {
                    "title": "Environment",
                    "value": "{{.app.spec.destination.namespace}}",
                    "short": true
                  },
                  {
                    "title": "Revision",
                    "value": "{{.app.status.sync.revision}}",
                    "short": true
                  },
                  {
                    "title": "Health",
                    "value": "{{.app.status.health.status}}",
                    "short": true
                  }
                ]
              }
            ]
          }

  # Trigger definitions
  trigger.on-deployed: |
    - description: "Application deployed"
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'

  trigger.on-health-degraded: |
    - description: "Application health degraded"
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'

  trigger.on-sync-failed: |
    - description: "Application sync failed"
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']

  trigger.on-sync-succeeded: |
    - description: "Application sync succeeded"
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']

  # Subscription configuration
  subscriptions: |
    - recipients:
      - email:platform-team@yourdomain.com
      triggers:
      - on-deployed
      - on-health-degraded
      - on-sync-failed
    - recipients:
      - webhook:generic
      triggers:
      - on-sync-succeeded
      - on-sync-failed