apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo-app-project
  namespace: argocd
  labels:
    app.kubernetes.io/name: todo-app-project
spec:
  description: "Project for todo-app and related services"

  # Source repositories allowed for this project
  sourceRepos:
    - https://github.com/sirhaffy/clo-k8s-inl01.git
    - https://charts.bitnami.com/bitnami    # For MongoDB
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

  # Destination clusters and namespaces
  destinations:
    - namespace: todo-app
      server: https://kubernetes.default.svc
    - namespace: mongodb
      server: https://kubernetes.default.svc

  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: secrets-store.csi.x-k8s.io
      kind: SecretProviderClass

  # Security policies
  roles:
    - name: developer
      description: "Developer access to todo-app"
      policies:
        - p, proj:todo-app-project:developer, applications, get, todo-app-project/*, allow
        - p, proj:todo-app-project:developer, applications, sync, todo-app-project/*, allow
        - p, proj:todo-app-project:developer, applications, action/*, todo-app-project/*, allow
        - p, proj:todo-app-project:developer, repositories, get, *, allow
      groups:
        - todo-app-developers

    - name: admin
      description: "Admin access to todo-app project"
      policies:
        - p, proj:todo-app-project:admin, applications, *, todo-app-project/*, allow
        - p, proj:todo-app-project:admin, repositories, *, *, allow
        - p, proj:todo-app-project:admin, certificates, *, *, allow
      groups:
        - todo-app-admins

  # Sync windows - when automatic sync is allowed
  syncWindows:
    - kind: allow
      schedule: "0 6-22 * * *"  # Allow sync between 06:00-22:00
      duration: 16h
      applications:
        - todo-app
      manualSync: true
    - kind: deny
      schedule: "0 22-6 * * *"  # Block automatic sync during night
      duration: 8h
      applications:
        - todo-app
      manualSync: true          # Still allow manual sync