apiVersion: v2
name: secrets
description: External secrets management for todo-app namespace
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - secrets
  - azure-keyvault
  - external-secrets
home: https://github.com/sirhaffy/clo-k8s-inl01
sources:
  - https://github.com/sirhaffy/clo-k8s-inl01
maintainers:
  - name: sirhaffy