name: Cleanup All Azure Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DELETE-ALL" to confirm complete cleanup'
        required: true
        type: string

jobs:
  cleanup:
    name: Delete Everything
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DELETE-ALL'

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete All Project Resources
        run: |
          echo "Starting complete cleanup..."

          # Delete main resource group (contains everything)
          if az group exists --name "rg-clo-k8s-inl01"; then
            echo "Deleting main resource group: rg-clo-k8s-inl01"
            az group delete --name "rg-clo-k8s-inl01" --yes --no-wait
          fi

          # Delete AKS managed resource group if it exists
          MC_RG=$(az group list --query "[?starts_with(name, 'MC_rg_clo_k8s_inl01')].name" -o tsv)
          if [ ! -z "$MC_RG" ]; then
            echo "Deleting AKS managed resource group: $MC_RG"
            az group delete --name "$MC_RG" --yes --no-wait
          fi

          # Delete terraform state resource group
          if az group exists --name "rg-terraform-state"; then
            echo "Deleting terraform state resource group: rg-terraform-state"
            az group delete --name "rg-terraform-state" --yes --no-wait
          fi

          echo "Cleanup initiated - all resources will be deleted"

      - name: Cleanup Summary
        run: |
          echo "##Complete Azure Cleanup Initiated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Deleted Resource Groups:**" >> $GITHUB_STEP_SUMMARY
          echo "- rg-clo-k8s-inl01 (main project resources)" >> $GITHUB_STEP_SUMMARY
          echo "- MC_rg_clo_k8s_inl01_* (AKS managed resources)" >> $GITHUB_STEP_SUMMARY
          echo "- rg-terraform-state (terraform state)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** All project resources deletion initiated" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY