name: CD Pipeline (Manual Deploy)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (e.g., v20241004-abc1234)'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Helm chart
      run: |
        echo "Updating Helm chart with image tag: ${{ inputs.image_tag }}"
        
        # Update deployment.yaml
        sed -i "s|image: haffy/todo-app:.*|image: haffy/todo-app:${{ inputs.image_tag }}|g" \
          helm/todo-app/templates/deployment.yaml
        
        # Update Chart.yaml
        sed -i "s|appVersion: .*|appVersion: \"${{ inputs.image_tag }}\"|g" \
          helm/todo-app/Chart.yaml

    - name: Commit updated charts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action CD"
        git add helm/
        git commit -m "deploy: update ${{ inputs.environment }} to ${{ inputs.image_tag }}"
        git push

    - name: Deploy info
      run: |
        echo "✅ Helm chart updated for ${{ inputs.environment }}"
        echo "📦 Image: haffy/todo-app:${{ inputs.image_tag }}"
        echo "🎯 ArgoCD will sync changes automatically"